config/routes.rb
Rails.application.routes.draw do

  resources :students do
    collection { post :import }
  end

#ensayo
  resources :hmcourses do
    collection { post :import }
  end

   get 'userposts' => 'user_posts#show'

  devise_for :users

   resources :constructions do
      resources :comments, only: [:create, :destroy]
   end

   root 'constructions#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id              :integer          not null, primary key
#  body            :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#  construction_id :integer
#

class Comment < ApplicationRecord
   belongs_to :user
   belongs_to :construction

   validates :body, presence: true
end

app/models/construction.rb
# == Schema Information
#
# Table name: constructions
#
#  id          :integer          not null, primary key
#  name        :string
#  image_url   :string
#  capacity    :integer
#  city        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Construction < ApplicationRecord
   #belongs_to :user
   has_many :comments, :dependent => :delete_all
   
   #validates :user, presence: true

   validates :name, :image_url, :capacity, :city, :description, :code, presence: true

   validates :city, format: { with: /\A[a-zA-Z\s+\D]+\z/,
       message: "Solo permite letras" }

   validates :description, length: {minimum: 10}
end

app/models/hmcourse.rb
class Hmcourse < ApplicationRecord
  require 'csv'

  def self.import(file)
    Hmcourse.delete_all
    CSV.foreach(file.path, headers:true) do |row|
      Hmcourse.create! row.to_hash 
    end
  end
end

app/models/pattern.rb
class Pattern < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  require 'csv'

  def self.import(file)
    Student.delete_all
    CSV.foreach(file.path, headers:true) do |row|
      Student.create! row.to_hash 
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
   #has_many :constructions, inverse_of: :user
   has_many :comments

   validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :warning, :danger, :info

  def private_access
    @postUser = Construction.find(params[:id]).user
    if @postUser != current_user
      flash[:danger] = "No tienes permiso para editar ese POST !!"
      redirect_to root_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   def create
      construction = Construction.find(params[:construction_id])
      construction.comments.create(comments_params)

      redirect_to construction
   end

   def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      flash[:info] = "Comentario eliminado exitosamente !!"
      redirect_to construction_path(@comment.construction.id)
   end

   private
     def comments_params
       params.require(:comment).permit(:body).merge(user: current_user)
     end
end

app/controllers/constructions_controller.rb
# Localmente debo usar LIKE --> SQLite
# En Heroku debo usar ILIKE --> PostgreSQL

class ConstructionsController < ApplicationController
   before_action :authenticate_user!
   before_action :private_access, only: [:edit]

   def index
      @constructions = Construction.order('created_at ASC')

      if params[:name].present? 
        @constructions = @constructions.where("name LIKE ? OR code LIKE ? OR city LIKE ?", 
         "%#{params[:name].strip}%","%#{params[:name].strip}%","%#{params[:name].strip}%")
      end
   end

   def new
      @construction = Construction.new
   end

   def create
      @construction = Construction.new(construction_params)
      @construction.user = current_user
      if @construction.save
         flash[:success] = "Curso creado exitosamente !!"
         redirect_to root_path
      else
         render :new
      end
   end

   def show
      @construction = Construction.find(params[:id])
   end

   def edit
      @construction = Construction.find(params[:id])
   end

   def update
      @construction = Construction.find(params[:id])
      if @construction.update(construction_params)
         flash[:info] = "Curso editado exitosamente !!"
         redirect_to root_path
      else
         render :edit
      end
   end

   def destroy
      @construction = Construction.find(params[:id])
      @construction.destroy
      flash[:info] = "Curso eliminado exitosamente !!"
      redirect_to root_path 
   end

   private
      def construction_params
         params.require(:construction).permit(:name, :image_url, :capacity, :city, :description, :code)
      end
end

app/controllers/hmcourses_controller.rb
class HmcoursesController < ApplicationController
  def index
    @hmcourses = Hmcourse.all
  end

  def import
    Hmcourse.import(params[:file])
    redirect_to hmcourses_url, notice: "Datos cargados con éxito"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def import
    Student.import(params[:file])
    redirect_to root_url, notice: "Datos cargados con éxito"
  end
end

app/controllers/user_posts_controller.rb
# Localmente debo usar LIKE --> SQLite
# En Heroku debo usar ILIKE --> PostgreSQL

class UserPostsController < ApplicationController
   before_action :authenticate_user!
   
   def show
     @posts = Construction.where("user_id = ?", current_user.id)

     if params[:name].present? 
       @posts = @posts.where("name ILIKE ?", "%#{params[:name].strip}%")
     end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
   def markdown(text)
     options = {
       filter_html:     true,
       hard_wrap:       true,
       link_attributes: { rel: 'nofollow', target: "_blank" },
       space_after_headers: true,
       fenced_code_blocks: true
     }

     extensions = {
       autolink:           true,
       superscript:        true,
       disable_indented_code_blocks: true
     }

     renderer = Redcarpet::Render::HTML.new(options)
     markdown = Redcarpet::Markdown.new(renderer, extensions)

     markdown.render(text).html_safe
   end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/constructions_helper.rb
module ConstructionsHelper
   def form_title
      @construction.new_record? ? "Nuevo Curso" : "Editar Curso"
   end

   def form_button
      @construction.new_record? ? "CREAR" : "EDITAR"
   end

   def form_button_class
      @construction.new_record? ? "success" : "warning"
   end
end

app/helpers/hmcourses_helper.rb
module HmcoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/views/constructions/_form.html.erb
<div class="container">
   <div class="row">
      <div class="col-xs-6 col-xs-offset-3">
         <h1 class="text-center" id="text-show"><%= form_title %></h1>   

         <%= form_for @construction do |f| %>

            <% if @construction.errors.any? %>
              <div class="alert alert-danger">
                <ul>
                <% @construction.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group">
               <%= f.text_field :name, class:"form-control input-lg", placeholder:"Nombre del Curso" %>
            </div>   

            <div class="form-group">
               <%= f.url_field :image_url, class:"form-control input-lg", placeholder:"URL de la foto del docente" %>
            </div>

            <div class="form-group">
               <%= f.number_field :capacity, :step => 1, class:"form-control input-lg", placeholder:"Cantidad de estudiantes" %>
            </div>

            <div class="form-group">
               <%= f.text_field :city, class:"form-control input-lg", placeholder:"Sede" %>
            </div>   

            <div class="form-group">
               <%= f.text_area :description, rows:"2", class:"form-control input-lg", placeholder:"Nombre del docente" %>
            </div>

            <div class="form-group">
               <%= f.submit form_button, class:"btn btn-#{form_button_class} btn-block btn-lg" %>
            </div>

         <% end %>
            
      </div>
   </div>
</div>

app/views/constructions/edit.html.erb
<%= render 'form' %>

app/views/constructions/index.html.erb
<% if Student.count == 0 %>
  <div class="col-sm-6 col-sm-offset-3">

    <div class="text-center" id="logo-eafit">
      <%= image_tag("logo_idiomas_eafit.png") %>
    </div>

    <div class="jumbotron">
      <h1 class="text-center">Bienvenido al Predictor de Idiomas EAFIT !!</h1>
    </div>

    <div class=" form-group text-center">
      <%= link_to "Comenzar", hmcourses_path, class:"btn btn-info btn-lg" %>
    </div>

  </div>

  <% else %>
  
  <% @constructions.each do |construction| %>
    <div class="container">
      <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
          <div class="thumbnail" id="boxes">
            <div class="col-xs-3" id="padding-images">
              <a href="<%= construction_path(construction.id) %>">
                <%= image_tag (construction.image_url), id:"index-images" %>
              </a>
            </div>

            <div class="col-xs-6">
              <h1 class="text-center">
                <%= link_to construction.name, construction_path(construction.id), id: "indexNames" %>
              </h1>

              <div id="infoThumbnail">

                <div class="text-center" id="text">
                  <label>CANTIDAD</label>
                  <p><%= construction.capacity %> Estudiantes </p>
                </div>
                
                <!-- <div class ="text-center" id="text">
                  <label>DOCENTE</label>
                  <p><%= construction.description %></p> 
                </div> -->

                <div class ="text-center" id="text">
                  <label>SESIÓN</label>
                  <p><%= construction.code %></p> 
                </div>

              </div>
              
            </div>  

            <div class="col-xs-3" id="infoSede">
              <div class ="text-center" id="text">
                <label>SEDE</label>
                <p id="text-sede"><%= construction.city %></p> 
              </div>
            </div>
          
          </div>
        </div>
      </div>
    </div>
  <% end %> 

<% end %>

app/views/constructions/new.html.erb
<%= render 'form' %>

app/views/constructions/show.html.erb

  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <div class="thumbnail" id="boxes">
          <div class="col-xs-3" id="padding_images">
            <div>
              <%= image_tag @construction.image_url, id:"show_image" %>
            </div>
            
          </div>

          <div class="col-xs-6">
            <h1 class="text-center" id="showNames">
              <%= @construction.name %>   
            </h1>

            <div id="info_Thumbnail">

              <div class="text-center" id="text">
                <label>CAPACIDAD</label>
                <p><%= @construction.capacity %> Estudiantes</p> 
              </div>
              
              <!-- <div class ="text-center" id="text">
                <label>DOCENTE</label>
                <p><%= @construction.description %></p> 
              </div> -->

              <div class ="pull-right" id="text">
                <label>SESIÓN</label>
                <p><%= @construction.code %></p> 
              </div>

            </div>
            

          </div>  

          
          <div class="col-xs-3" id="infoSede">
            <div class ="text-center" id="text">
              <label>SEDE</label>
              <p id="text-sede"><%= @construction.city %></p> 
            </div>
          </div>
          
        
        </div>
      </div>
    </div>
  </div>







<div class="container">
  <div class="col-xs-5" id="text-show">
    <h3>Comentarios ( <%= @construction.comments.count %> )</h3>
    <hr>
    <% @construction.comments.each do |comment| %>

      <div class="panel panel-default">
        <div class="panel-heading" id="panelComments">
          <strong><%= comment.user.email %> comentó hace <%= time_ago_in_words(comment.created_at) %></strong>
        </div>

        <div class="panel-body" id="text_controller">
          <%= comment.body %>
          <% if user_signed_in? && comment.user == current_user %>
            <strong><%= link_to "Eliminar", [comment.construction, comment], :method => :delete, class:"pull-right" %></strong>
          <% end %>
        </div>
        
      </div>

    <% end %>

    <% if user_signed_in? %>
      <%= form_for([@construction, @construction.comments.build]) do |f| %>

        <div class="form-group">
          <h4>Nuevo Comentario</h4>
          <%= f.text_area :body, class:"form-control", placeholder:"Ingresa tu comentario" %>
        </div>

        <div class="form-group">
          <%= f.submit "Comentar", class:"btn btn-primary" %>
        </div>
        <br>

      <% end %>
    <% end %>
    
  </div>
</div>

app/views/hmcourses/index.html.erb
<div class="container text-center">
  <div class="row">
    <h1>Cursos</h1>

    <%= form_tag import_hmcourses_path, multipart: true do %>

      <span class="btn btn-lg btn-warning" >
        <%= file_field_tag :file %>
      </span>
      
      <br>
      <span>
        <%= submit_tag "Enviar",class:"btn btn-lg btn-info", id:"boton" %>
      </span>  
      
    <% end %>

    <h1>Estudiantes</h1>
    <%= form_tag import_students_path, multipart: true do %>

      <span class="btn btn-lg btn-warning" >
        <%= file_field_tag :file %>
      </span>
      
      <br>
      <span>
        <%= submit_tag "Enviar",class:"btn btn-lg btn-info", id:"boton" %>
      </span>  
      
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb

<div class="row">
    <% flash.each do |type, msg| %>
      <% if type == "success" %>
        <div class="col-xs-10 col-xs-offset-1">
          <div class="alert alert-success">
      <% elsif type == "alert" %>
        <div class="col-xs-4 col-xs-offset-4">
          <div class="alert alert-danger">
      <% elsif type == "info" || type == "notice" %>
        <div class="col-xs-10 col-xs-offset-1">
          <div class="alert alert-info">
      <% else %>
        <div class='alert alert-<%= "#{type}" %>'>
      <% end %>
          <div class="text-center">
            <%= msg %>
          </div>
        </div>
    <% end %>
</div>
       

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> | Kronos Evolution | </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-inverse">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <%= link_to "Kronos Evolution", root_path, class:"navbar-brand", id:"navbar_brand" %> 
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path, class:"active", id:"navbar_links" %></li>
        </ul>

        <form class="navbar-form navbar-left">
          <div class="form-group">
            <%= form_tag constructions_path, method: :get do %>  
              <%= text_field_tag :name, params[:name], class: "form-control", placeholder: "Buscar por parámetro .." %>  

              <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>  
            <% end %>
          </div>
       </form>
          
        <ul class="nav navbar-nav navbar-right">
   
          <% if user_signed_in? %>
            <!-- <li><%= link_to "Nuevo Curso", new_construction_path, id:"navbar_links" %></li> -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="navbar_links"><span class="glyphicon glyphicon-user"></span> <%= current_user.email[0..current_user.email.index('@')-1] %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                
                <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>

            <% else %>
            <li><%= link_to "Registrarse", new_user_registration_path, id:"navbar_links" %></li>
            <li><%= link_to "Ingresar", new_user_session_path, id:"navbar_links" %></li>
            
          <% end %>
          
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


    <%= render 'layouts/messages' %>
    
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<div class="container text-center">
  <div class="row">
    <h1>Importar los datos!</h1>

    <%= form_tag import_students_path, multipart: true do %>

      <span class="btn btn-lg btn-warning" >
        <%= file_field_tag :file %>
      </span>
      
      <br>
      <span>
        <%= submit_tag "Enviar", class:"btn btn-lg btn-info", id:"boton" %>
      </span>  
      
    <% end %>
  </div>
</div>

app/views/user_posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <br><br>
      <% if current_user.constructions.count == 0 %>
        <div class="col-xs-6 col-xs-offset-3">
            <div class="jumbotron">
              <h2 class="text-center">Aún no tienes publicaciones</h2>
            </div>
        </div>

        <div class="col-xs-4 col-xs-offset-4">
          <br><h2><%= link_to "CREAR MI PRIMER POST", new_construction_path, class:"btn btn-block btn-lg btn-primary" %></h2>  
        </div>
      <% end %>  
        

      <% @posts.each do |post| %>
        <% if @posts.count  == 1  %>
          <div class="col-xs-4 col-xs-offset-4">
        <% elsif @posts.count % 3 == 0 || @posts.count % 2 == 1  %>
          <div class="col-xs-4">
        <% elsif @posts.count % 2 == 0 %>
          <div class="col-xs-4 col-xs-offset-1">
        <% end %>

        <div class="thumbnail" id="userPosts-boxes">
          <a href="<%= construction_path(post.id) %>">
            <%= image_tag post.image_url, id:"index-images" %>
          </a>

          <div class="text-center">
            <%= link_to post.name, construction_path(post.id), id:"userPosts-titles" %><br>

             <% if user_signed_in? && post.user == current_user %>
               <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_construction_path(post), id:"edit_button" %>

               <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, post, data: { confirm: "Are you sure?" }, method: :delete, id:"delete_button" %>
             <% end %>
          </div>
        </div>
    </div>   
      <% end %>
  </div>
</div>